name: ç½‘ç«™éƒ¨ç½²ï¼Œæ„å»º
on: [push, repository_dispatch]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: é€‰æ‹©é»˜è®¤åˆ†æ”¯æ„å»º ğŸ›ï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
      - name: å®‰è£…nodeç¯å¢ƒ ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          yarn
          yarn build
      - name: ç½‘ç«™éƒ¨ç½²
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_branch: master
          publish_dir: ./dist
          commit_message: auto deploy
      - name: é€‰æ‹©æ•°æ®åˆ†æ”¯æ„å»º
        uses: actions/checkout@v2
        with:
          ref: data
        run:
          export COS_SECRETID=${{ secrets.COS_SECRETID }} && export COS_SECRETKEY=${{ secrets.COS_SECRETKEY }} && go run main.go
